import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar.js";
import { Toaster } from "@/components/ui/toaster.jsx";
import QueryProvider from "@/lib/react-query/QueryProvider.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <main className="flex min-h-screen w-full max-w-[1600px] relative mx-auto flex-col">
            <Navbar />
            {children}
          <Toaster />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
